import type { DailyQuest } from "@family-game/domain";

export const DEMO_QUESTS: DailyQuest[] = [
  {
    id: "demo-dishes",
    householdId: "demo-household",
    templateId: "template-dishes",
    title: "Dishes",
    instruction: "Clear the dishes, wash what needs washing, and leave the sink ready for the next meal.",
    spokenInstruction: "The dishes need us. Clear, wash, and leave the sink ready.",
    kind: "open",
    state: "needed",
    effort: "light",
    appreciationValue: 1,
    contributionValue: 1,
    icon: "dishes",
    participantIds: [],
    suggestedMemberIds: [],
    dueDate: "2026-07-22",
    urgency: 2,
    completedAt: null,
  },
  {
    id: "demo-laundry",
    householdId: "demo-household",
    templateId: "template-laundry",
    title: "Pack away laundry",
    instruction: "Work together to sort and return the clean clothes to their homes.",
    spokenInstruction: "Team quest. Sort the clean clothes and put them away together.",
    kind: "duo",
    state: "active",
    effort: "medium",
    appreciationValue: 2,
    contributionValue: 2,
    icon: "laundry",
    participantIds: ["demo-ayla", "demo-child"],
    suggestedMemberIds: ["demo-ayla", "demo-child"],
    dueDate: "2026-07-22",
    urgency: 1,
    completedAt: null,
  },
  {
    id: "demo-kitchen",
    householdId: "demo-household",
    templateId: "template-kitchen",
    title: "Tidy kitchen",
    instruction: "Give the kitchen a ten-minute family reset so tomorrow starts gently.",
    spokenInstruction: "Whole home quest. Everyone helps reset the kitchen for ten minutes.",
    kind: "family",
    state: "needed",
    effort: "medium",
    appreciationValue: 2,
    contributionValue: 2,
    icon: "home",
    participantIds: [],
    suggestedMemberIds: ["demo-ayla", "demo-partner", "demo-child"],
    dueDate: "2026-07-22",
    urgency: 0,
    completedAt: null,
  },
  {
    id: "demo-reading",
    householdId: "demo-household",
    templateId: "template-reading",
    title: "Reading",
    instruction: "Read together or independently for fifteen calm minutes.",
    spokenInstruction: "Reading is done and waiting for someone to send thanks.",
    kind: "personal",
    state: "pending_endorsement",
    effort: "light",
    appreciationValue: 1,
    contributionValue: 1,
    icon: "book",
    participantIds: ["demo-child"],
    suggestedMemberIds: ["demo-child"],
    dueDate: "2026-07-22",
    urgency: 0,
    completedAt: null,
  },
  {
    id: "demo-plants",
    householdId: "demo-household",
    templateId: "template-plants",
    title: "Water plants",
    instruction: "Check the soil first, then give the thirsty plants a drink.",
    spokenInstruction: "The plants are thirsty. Check the soil, then give them a drink.",
    kind: "care",
    state: "needed",
    effort: "light",
    appreciationValue: 1,
    contributionValue: 1,
    icon: "plant",
    participantIds: [],
    suggestedMemberIds: [],
    dueDate: "2026-07-22",
    urgency: 1,
    completedAt: null,
  }
];
