import type { Household } from "@family-game/domain";

export const DEMO_HOUSEHOLD: Household = {
  id: "demo-household",
  name: "Our Home",
  timezone: "Africa/Johannesburg",
  quietHoursStart: "20:00",
  quietHoursEnd: "07:00",
  motto: "Every side helps. Together, we find our balance.",
  members: [
    {
      id: "demo-ayla",
      householdId: "demo-household",
      displayName: "Ayla",
      initials: "A",
      role: "adult",
      colour: "#ee6c58",
      pointLabel: "High Fives",
      contributionTarget: 10,
      symbol: "sun",
    },
    {
      id: "demo-partner",
      householdId: "demo-household",
      displayName: "Raen",
      initials: "R",
      role: "adult",
      colour: "#2b78a0",
      pointLabel: "High Fives",
      contributionTarget: 10,
      symbol: "mountain",
    },
    {
      id: "demo-child",
      householdId: "demo-household",
      displayName: "Sage",
      initials: "S",
      role: "child",
      colour: "#e4a72e",
      pointLabel: "High Fives",
      contributionTarget: 4,
      symbol: "star",
    },
  ],
};
